[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'hardhat/=node_modules/hardhat/',
    'solady/=lib/solady/src/',
    'solmate/=lib/solmate/src/',
    '@openzeppelin/=node_modules/@openzeppelin/'
]

[invariant]
runs = 1000

[fmt]
bracket_spacing = true
line_length = 120
number_underscore = 'thousands'
wrap_comments = true